services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks:
      ip_vlan:
        ipv4_address: 192.168.10.20
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/Caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/Caddy/data:/data
      - /home/Caddy/config:/config
networks:
  ip_vlan:
    external: true
