version: "3.9"

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    networks:
      caddy_ipvlan:
        ipv4_address: 192.168.1.2
    volumes:
      - /home/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /home/caddy/data:/data
      - /home/caddy/config:/config
    environment:
      - TZ=UTC
networks:
  caddy_ipvlan:
    external: true
