version: "3.9"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    networks:
      ip_vlan:
        ipv4_address: 192.168.10.2
    environment:
      TZ: "Etc/UTC"
      WEBPASSWORD: "Pa$$w0rd"
      FTLCONF_LOCAL_IPV4: "192.168.10.2"
      DNSMASQ_LISTENING: "all"
      QUERY_LOGGING: "true"
    volumes:
      - /docker/pihole/etc-pihole:/etc/pihole
      - /docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "80:8096"
    user: "1000:1000"
    networks:
      ip_vlan:
        ipv4_address: 192.168.10.4
    environment:
      JELLYFIN_HTTP_PORT: "80"
    volumes:
      - /srv/storage/jellyfin/cache:/cache
      - /srv/storage/jellyfin/config:/config
      - /srv/storage/jellyfin/media:/media:ro

  dashy:
    image: lissy93/dashy
    container_name: dashy
    restart: unless-stopped
    networks:
      ip_vlan:
        ipv4_address: 192.168.10.5
    environment:
      NODE_ENV: production
      UID: "1000"
      GID: "1000"
      PORT: "80"
    volumes:
      - /home/dashy/conf.yml:/app/user-data/conf.yml
      
   bitwarden:
     image: vaultwarden/server:latest
     container_name: bitwarden
     restart: unless-stopped
     networks:
       ip_vlan:
         ipv4_address: 192.168.10.6
     volumes:
       - /home/bitwarden/bw-data:/data
     environment:
       WEBSOCKET_ENABLED: 'true'
       SIGNUPS_ALLOWED: 'false'

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    networks:
      ip_vlan:
        ipv4_address: 192.168.10.20
    ports:
    - "80:80"
    - "443:443"
    - "81:81"
    volumes:
    - /home/nginx/data:/data
    - /home/nginx/letsencrypt:/etc/letsencrypt

networks:
  ip_vlan:
    external: true
