version: "3.9"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    networks:
      ip_vlan:
        ipv4_address: 192.168.10.2
    environment:
      TZ: "Etc/UTC"
      WEBPASSWORD: "Pa$$w0rd"
      FTLCONF_LOCAL_IPV4: "192.168.10.2"
      DNSMASQ_LISTENING: "all"
      QUERY_LOGGING: "true"
    volumes:
      - /docker/pihole/etc-pihole:/etc/pihole
      - /docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    user: "1000:1000"
    networks:
      ip_vlan:
        ipv4_address: 192.168.10.3
    environment:
      JELLYFIN_HTTP_PORT: "80"
    volumes:
      - /home/jellyfin/cache:/cache
      - /home/jellyfin/config:/config
      - /home/jellyfin/media:/media:ro

  dashy:
    image: lissy93/dashy
    container_name: dashy
    restart: unless-stopped
    networks:
      ip_vlan:
        ipv4_address: 192.168.10.4
    environment:
      NODE_ENV: production
      UID: "1000"
      GID: "1000"
      PORT: "80"
    volumes:
      - /home/Dashy/conf.yml:/app/user-data/conf.yml
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ip_vlan:
    external: true
