version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      jellyfin_ipvlan:
        ipv4_address: 192.168.1.4
    volumes:
      - /home/jellyfin/cache:/cache
      - /home/jellyfin/config:/config
      - /home/jellyfin/media:/media:ro
    restart: unless-stopped
networks:
  jellyfin_ipvlan:
    external: true
