pageInfo:
  title: Home Lab
appConfig:
  theme: nord-frost
sections:
- name: Productivity
  displayData:
    collapsed: false
    cols: 2
  items:
  - title: Archive Box
    description: Web site archiving
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/archivebox.png
  - title: Baserow
    description: Feature-rich dynamic tables
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/baserow.png
  - title: Bookstack
    description: Self-hosted Wiki
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/bookstack.png
  - title: Domain Mod
    description: Manage domains and other internet assets
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/domainmod.png
  - title: Firefly
    description: Financial manager
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/firefly-iii.png
  - title: Fresh RSS
    description: RSS feed reader
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/freshrss.png
  - title: GifWit
    description: Personal GIF library
    icon: far fa-images
  - title: Git Tea
    description: Git service
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/gitea.png
  - title: LessPass
    description: Deterministic stateless password manager
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/lesspass.png
  - title: NextCloud
    description: Cloud office suit
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/nextcloud.png
  - title: Paperless
    description: Scan and archive documents
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/paperless-ngx.png
  - title: Photo Prism
    description: Browsing and organizing photos
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/photoprism.png
  - title: Standard Notes
    description: Encrypted notes app
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/standard-notes.png
  - title: Syncthing
    description: Peer-to-peer file synchronization
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/syncthing.png
  - title: VS Code Web
    description: Cloud based development
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/visual-studio-code.png
  - title: Wallabag
    description: Saved URLs and bookmarks
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/wallabag.png
  - title: XBrowserSync
    description: Bookmarks and browser sync
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/xbrowsersync.png
- name: Firewall
  items:
  - title: OPNsense
    description: Firewall Central Management
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/opnsense.png
    target: iframe
  - title: NetData
    description: System resource usage
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/netdata.png
  - title: MalTrail
    description: Malicious traffic detection
    icon: fas fa-shield-alt
  - title: Ntopng
    description: Network traffic probe
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/ntopng.png
  - title: Sensei
    description: Additional data features
    icon: fas fa-project-diagram
  - title: Monit
    description: Status alerts
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/monit.png
  - title: Firewall Logs
    description: Real-time logs
    icon: fas fa-terminal
  - title: WireGuard
    description: Manage WireGuard
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/wireguard.png
- name: Networks
  items:
  - title: Pi-Hole
    description: DNS settings
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/pi-hole.png
  - title: PiAlert
    description: Presence monitoring
    icon: fas fa-bell
  - title: SmokePing
    description: Network latency monitoring
    icon: fas fa-chart-line
  - title: StatPing
    description: Up-time monitoring
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/statping.png
  - title: LibreSpeed
    description: Local network speed test
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/librespeed.png
  - title: Grafana
    description: Data visualised
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/grafana.png
- name: System Maintence
  items:
  - title: NetData
    description: Real-time usage
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/netdata.png
  - title: Portainer
    description: Docker management
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/portainer.png
  - title: cAdvisor
    description: Container monitoring
    icon: fas fa-microchip
  - title: Glances
    description: Simple resource usage
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/glances.png
  - title: Dozzle
    description: Docker log viewer
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/dozzle.png
  - title: Prometheus
    description: Statistics Aggregation
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/prometheus.png
- name: External Services
  items:
  - title: DuckDNS
    description: Dynamic DNS
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/duckdns.png
  - title: BorgBase
    description: Off-site backups
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/borgbackup.png
    url: https://www.borgbase.com/repositories
  - title: Mullvad
    description: Hosted VPN provider
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/mullvad.png
    url: https://mullvad.net/en/account/
  - title: ZeroTier
    description: Secure networks
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/zerotier.png
    url: https://my.zerotier.com/
  - title: HealthChecks
    description: Cron Job Monitoring
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/healthchecks.png
    url: https://healthchecks.io/checks/
  - title: ISP - Vodafone
    description: Broadband provider
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/vodafone.png
    url: https://myaccount.vodafone.co.uk/
- name: Media
  items:
  - title: Plex
    description: Media Streaming
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/plex.png
  - title: Tautulli
    description: Monitoring for Plex
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/tautulli.png
  - title: Transmission
    description: Transmission remote
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/transmission.png
  - title: Couch Potato
    description: Automatic Movie Downloading
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/couch-potato.png
- name: Home Control
  items:
  - title: Home Assistant
    description: Smart home control
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/home-assistant.png
  - title: Node-RED
    description: Flow-based automation
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/node-red.png
- name: Other Devices
  items:
  - title: Modem
    description: ISP Router Modem Combo
    icon: fas fa-router
  - title: Wireless Access Point
    description: View clients connected to WiFi
    icon: fas fa-wifi
  - title: Fing
    description: Monitor connectivity
    icon: favicon-https://app.fing.com/
    url: https://app.fing.com/
  - title: Switch
    description: Manage VLANs
    icon: fas fa-network-wired
- name: External Utilities
  displayData:
    collapsed: true
  items:
  - title: Public IP
    description: Check public IP
    icon: fas fa-globe
    url: https://www.whatismyip.com/
  - title: Who Is Lookup
    description: Check ICAN info
    icon: fas fa-search-location
    url: https://whois.domaintools.com/
  - title: Speed Test
    description: Upload + download speeds
    icon: fas fa-tachometer-alt
    url: https://speed.cloudflare.com/
  - title: Mullvad Check
    description: Confirms secure connection
    icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/mullvad.png
    url: https://mullvad.net/check
